# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('user_type', models.CharField(choices=[('AM', 'ADMINISTRADOR'), ('PR', 'PROPIETARIO'), ('CH', 'CHOFER')], default='CH', max_length=50)),
                ('image', models.ImageField(blank=True, default='/profile-images/empty.jpg', upload_to='/profile-images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxiTec.UserProfile'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxiTec.UserProfile'),
        ),
        migrations.AddField(
            model_name='admin',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxiTec.UserProfile'),
        ),
    ]
