# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='name_owner',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile-images/empty.jpg', upload_to='profile-images/'),
        ),
    ]
