# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0003_auto_20170402_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='XXXXXXXXXX', max_length=10),
        ),
    ]
