# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0004_auto_20170402_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='XX', max_length=10),
        ),
    ]
