# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0005_auto_20170402_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name_admin',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name_driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'Tipo O+'), ('O-', 'Tipo O-'), ('A+', 'Tipo A+'), ('A-', 'Tipo A-'), ('B+', 'Tipo B+'), ('B-', 'Tipo B-'), ('AB+', 'Tipo AB+'), ('AB-', 'Tipo AB-')], default='O-', max_length=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number_2',
            field=models.CharField(default='XX', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxiTec.Driver'),
        ),
    ]
