# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0007_auto_20170402_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
