# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0012_auto_20170402_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='taxiTec.Owner'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'Tipo O+'), ('O-', 'Tipo O-'), ('A+', 'Tipo A+'), ('A-', 'Tipo A-'), ('B+', 'Tipo B+'), ('B-', 'Tipo B-'), ('AB+', 'Tipo AB+'), ('AB-', 'Tipo AB-')], default='O-', max_length=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number_2',
            field=models.CharField(blank=True, default='XX', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='XXXXXXXXXX', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AM', 'ADMINISTRADOR'), ('PR', 'PROPIETARIO'), ('CH', 'CHOFER')], default='CH', max_length=50),
        ),
    ]
