# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0016_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='numero',
            new_name='number',
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='plates',
            field=models.CharField(default='XXX-XXX', max_length=7),
        ),
    ]
