# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0017_auto_20170430_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiTec.Owner'),
        ),
    ]
