# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0019_ingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='ingreso',
            field=models.FloatField(default=0),
        ),
    ]
