# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0021_ingresos_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='driver',
        ),
    ]
