# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0022_remove_ingresos_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxiTec.Driver'),
            preserve_default=False,
        ),
    ]
