# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiTec', '0024_auto_20170515_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxiTec.Owner'),
        ),
    ]
